version: '2'
services:
    skylark-app-prod:
        image: docker.cloudspace.pw/skylark-backend:prod
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://skylark-mysql-prod:3306/skylark?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=skylark-elasticsearch-prod:9300
        ports:
            - 8080:8080
    skylark-mysql-prod:
        extends:
            file: mysql.yml
            service: skylark-mysql-prod
    skylark-elasticsearch-prod:
        extends:
            file: elasticsearch.yml
            service: skylark-elasticsearch-prod
