version: '2'
services:
    skylark-app-testing:
        image: docker.cloudspace.pw/skylark-backend:testing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://skylark-mysql-testing:3306/skylark?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=skylark-elasticsearch-testing:9300
        ports:
            - 8082:8080
        volumes:
            - ~/volumes/jhipster/skylark/testing/app/:/root/
    skylark-mysql-testing:
        extends:
            file: mysql.yml
            service: skylark-mysql-testing
    skylark-elasticsearch-testing:
        extends:
            file: elasticsearch.yml
            service: skylark-elasticsearch-testing
