version: '2'
services:
    skylark-mysql-testing:
        image: mysql:5.7.20
        volumes:
            - ~/volumes/jhipster/skylark/testing/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=E6upVWmvE1OWIQaDN3c7
            - MYSQL_ROOT_PASSWORD=E6upVWmvE1OWIQaDN3c7
            - MYSQL_DATABASE=skylark
        ports:
            - 3308:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --max_allowed_packet=1073741824
