version: '2'
services:
    skylark-elasticsearch-staging:
        image: elasticsearch:2.4.6
        volumes:
            - ~/volumes/jhipster/skylark/staging/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9201:9200
            - 9301:9300
